name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ---------- CHOMP ----------
      - name: Build chomp
        run: |
          pip install build setuptools-scm
          SETUPTOOLS_SCM_ROOT=.. python -m build chomp
          mkdir -p dist/chomp
          cp chomp/dist/* dist/chomp/

      # ---------- MUFFIN ----------
      - name: Build muffin
        run: |
          mkdir -p dist/muffin_stage

          rsync -a muffin/ dist/muffin_stage/ --exclude=".*"

          tar -czf dist/muffin.tar.gz -C dist/muffin_stage .
          zip -r dist/muffin.zip dist/muffin_stage

      # ---------- RELEASE ----------
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/chomp/*
            dist/muffin.tar.gz
            dist/muffin.zip
